### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by ghost** [trvrb/wave#1]
@trvrb Could you please tell me how to run it, thanks.

**Comment by trvrb** [comment]
Good question. I added instructions to readme in this commit: https://github.com/trvrb/wave/commit/3b8d04ccf9c2fe7080c8291e50adee3bc3bc391f

**Comment by ghost** [comment]
@thanks, @trvrb what will be the results, thanks.

**Comment by ghost** [comment]
I run it very long time, when will it be finished, thanks.
